server.port=8085

spring.application.name=card-benefit-notification-server
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=card_benefit
spring.datasource.password=abcd1234

spring.kafka.bootstrap-servers=localhost:9092

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.cardbenefit.notification.dto
mybatis.configuration.map-underscore-to-camel-case=true