server.port=8086

spring.application.name=card-benefit-payment-server
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=card_benefit
spring.datasource.password=abcd1234

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.cardbenefit.payment.dto
mybatis.configuration.map-underscore-to-camel-case=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379


# 카카오페이
kakao.pay.rest-api-key=DEVA76F7625E9B66925F76DCFD602971EE644FBF
kakao.pay.cid=TC0ONETIME
kakao.pay.ready-url=https://open-api.kakaopay.com/online/v1/payment/ready
kakao.pay.approve-url=https://open-api.kakaopay.com/online/v1/payment/approve


jwt.secret=card-benefit-secret-key-must-be-at-least-256-bits-long
jwt.expiration=86400000
kakao.pay.cancel-url=https://open-api.kakaopay.com/online/v1/payment/cancel